#!/usr/bin/env python3
"""
build.py — single-source site/CV generator for Ghulam Murtaza's webpage.

Reads:
    data/publications.bib   (papers; the only place you add publications)
    data/talks.yaml         (talks + posters)
    data/teaching.yaml      (courses)
    data/mentoring.yaml     (student advising)
    data/about.yaml         (landing page content)

Writes:
    cv/generated/*.tex      (\\input into cv/cv.tex — preserves the res.cls look)
    site/*.html             (the website pages)

No third-party deps except PyYAML. The BibTeX parser is a small self-contained
one (below) so there's nothing else to install in CI.
"""

import datetime
import html
import os
import re

import yaml

# Build/deploy time, shown in the site footer and at the end of the CV.
_BUILD_DT = datetime.datetime.now(datetime.timezone.utc)
BUILD_STAMP = f"{_BUILD_DT:%B} {_BUILD_DT.day}, {_BUILD_DT:%Y} at {_BUILD_DT:%H:%M} UTC"

ROOT = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(ROOT, "data")
SITE = os.path.join(ROOT, "site")
GEN = os.path.join(ROOT, "cv", "generated")

# Custom .bib fields used only by this script (never shown in [BibTeX]).
PRIVATE_FIELDS = {"pubtype", "venue", "status", "award", "pdf", "code", "arxiv", "slides"}

GEN_HEADER = "% AUTO-GENERATED by build.py — do not edit. Edit data/ instead.\n"

# Order in which standard fields are emitted in the displayed BibTeX block.
BIBTEX_FIELD_ORDER = [
    "title", "author", "journal", "booktitle", "year", "volume",
    "number", "pages", "publisher", "doi", "url",
]


# --------------------------------------------------------------------------- #
#  Minimal BibTeX parser
# --------------------------------------------------------------------------- #
def parse_bib(text):
    """Parse a .bib string into a list of {type, key, fields, order}."""
    entries = []
    i, n = 0, len(text)
    while True:
        at = text.find("@", i)
        if at == -1:
            break
        brace = text.find("{", at)
        if brace == -1:
            break
        etype = text[at + 1:brace].strip().lower()
        # Read the balanced { ... } body.
        depth, j = 0, brace
        while j < n:
            c = text[j]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        body = text[brace + 1:j]
        i = j + 1
        if etype in ("comment", "preamble", "string"):
            continue

        comma = body.find(",")
        if comma == -1:
            continue
        key = body[:comma].strip()
        rest = body[comma + 1:]

        order = []
        fields = {}
        p, m = 0, len(rest)
        while p < m:
            while p < m and rest[p] in " \t\r\n,":
                p += 1
            if p >= m:
                break
            eq = rest.find("=", p)
            if eq == -1:
                break
            fname = rest[p:eq].strip().lower()
            q = eq + 1
            while q < m and rest[q] in " \t\r\n":
                q += 1
            if q < m and rest[q] == "{":
                d, r = 0, q
                while r < m:
                    if rest[r] == "{":
                        d += 1
                    elif rest[r] == "}":
                        d -= 1
                        if d == 0:
                            break
                    r += 1
                val = rest[q + 1:r]
                p = r + 1
            elif q < m and rest[q] == '"':
                r = q + 1
                while r < m and rest[r] != '"':
                    r += 1
                val = rest[q + 1:r]
                p = r + 1
            else:
                r = q
                while r < m and rest[r] not in ",\n":
                    r += 1
                val = rest[q:r].strip()
                p = r
            val = " ".join(val.split())
            if fname:
                fields[fname] = val
                order.append(fname)
        entries.append({"type": etype, "key": key, "fields": fields, "order": order})
    return entries


# --------------------------------------------------------------------------- #
#  Author name helpers
# --------------------------------------------------------------------------- #
def split_authors(s):
    return [a.strip() for a in re.split(r"\s+and\s+", s) if a.strip()]


def name_parts(author):
    """Return (last_name, [given_tokens]) from a 'Last, First M' or 'First Last' string."""
    if "," in author:
        last, firsts = author.split(",", 1)
        last, firsts = last.strip(), firsts.strip()
    else:
        toks = author.split()
        last, firsts = (toks[-1] if toks else author), " ".join(toks[:-1])
    given = [t for t in re.split(r"[\s.]+", firsts) if t]
    return last, given


def is_me(last):
    return last.lower() == "murtaza"


# Lists longer than this are truncated to "first 3, ..., <me>, et al." so giant
# consortium papers don't blow up the CV/site. The [BibTeX] block always keeps
# the full list.
MAX_AUTHORS = 20


def _one_cv(author):
    last, given = name_parts(author)
    initials = "".join(t[0].upper() for t in given)
    name = (last + " " + initials).strip()
    return r"\textbf{" + name + "}" if is_me(last) else name


def _one_web(author):
    last, given = name_parts(author)
    # If a given token is a single letter, render it as an initial with a dot.
    rendered = " ".join((t if len(t) > 1 else t + ".") for t in given)
    full = h((rendered + " " + last).strip())
    return f"<strong>{full}</strong>" if is_me(last) else full


def _render_authors(author_field, render_one, ellipsis):
    authors = split_authors(author_field)
    rendered = [render_one(a) for a in authors]
    if len(rendered) <= MAX_AUTHORS:
        return ", ".join(rendered)
    me_idx = next((i for i, a in enumerate(authors) if is_me(name_parts(a)[0])), None)
    head = rendered[:3]
    if me_idx is not None and me_idx >= 3:
        return ", ".join(head) + f", {ellipsis} " + rendered[me_idx] + ", et al."
    return ", ".join(head) + ", et al."


def authors_cv(author_field):
    """CV style: 'Fang T, Wang X, \\textbf{Murtaza G}, ...'."""
    return _render_authors(author_field, _one_cv, r"\ldots")


def authors_web(author_field):
    """Website style: 'Tangqi Fang, ..., <strong>Ghulam Murtaza</strong>, ...' (HTML)."""
    return _render_authors(author_field, _one_web, "&hellip;")


# --------------------------------------------------------------------------- #
#  Escaping
# --------------------------------------------------------------------------- #
_LATEX_ESCAPES = {"&": r"\&", "%": r"\%", "#": r"\#", "_": r"\_"}


def tex_escape(s):
    return "".join(_LATEX_ESCAPES.get(c, c) for c in s)


# LaTeX accent command -> combining Unicode codepoint, for HTML rendering.
_ACCENTS = {
    '"': "̈", "'": "́", "`": "̀", "^": "̂",
    "~": "̃", "=": "̄", ".": "̇", "v": "̌",
    "c": "̧", "u": "̆", "H": "̋",
}
_ACCENT_RE = re.compile(r'\{?\\(?P<acc>["\'`^~=.vcuH])\{?(?P<ch>[A-Za-z])\}?\}?')


def delatex(s):
    """Turn LaTeX accents like {\\"u} into real Unicode (ü) and drop stray braces."""
    def repl(m):
        comb = _ACCENTS.get(m.group("acc"))
        ch = m.group("ch")
        return __import__("unicodedata").normalize("NFC", ch + comb) if comb else ch
    s = _ACCENT_RE.sub(repl, s)
    return s.replace("{", "").replace("}", "")


def h(s):
    """Escape for HTML display, converting LaTeX accents to Unicode."""
    return html.escape(delatex(s), quote=True)


def h_raw(s):
    """Escape for HTML without touching LaTeX (used for the copy-paste BibTeX)."""
    return html.escape(s, quote=True)


# --------------------------------------------------------------------------- #
#  Publications
# --------------------------------------------------------------------------- #
def load_publications():
    with open(os.path.join(DATA, "publications.bib"), encoding="utf-8") as f:
        entries = parse_bib(f.read())
    for e in entries:
        e["year"] = int(re.sub(r"\D", "", e["fields"].get("year", "0")) or 0)
        e["pubtype"] = e["fields"].get("pubtype", "journal").lower()
    return entries


def cv_pub_line(e):
    """One CV paragraph for a publication, matching the original styling."""
    f = e["fields"]
    authors = authors_cv(f.get("author", ""))
    title = tex_escape(f.get("title", ""))
    if e["pubtype"] == "preprint" and f.get("status"):
        italic = tex_escape(f["status"])
    else:
        italic = tex_escape(f.get("venue", f.get("journal", f.get("booktitle", ""))))
    asep = "" if authors.endswith(".") else "."
    line = f"{authors}{asep} {title}. \\textit{{{italic}}}."
    if f.get("award"):
        line += f" ({tex_escape(f['award'])})"
    return line


def clean_bibtex(e):
    """Re-emit a tidy BibTeX entry with private fields stripped (for the website)."""
    fields = {k: v for k, v in e["fields"].items() if k not in PRIVATE_FIELDS}
    ordered = [k for k in BIBTEX_FIELD_ORDER if k in fields]
    ordered += [k for k in fields if k not in ordered]
    lines = [f"@{e['type']}{{{e['key']},"]
    for k in ordered:
        lines.append(f"  {k:<9}= {{{fields[k]}}},")
    if len(lines) > 1:
        lines[-1] = lines[-1].rstrip(",")
    lines.append("}")
    return "\n".join(lines)


def web_pub_item(e):
    """One <li> for the publications page, with a [BibTeX] <details> dropdown."""
    f = e["fields"]
    authors = authors_web(f.get("author", ""))
    title = h(f.get("title", ""))
    if e["pubtype"] == "preprint":
        venue = f.get("venue") or f.get("status") or f.get("journal", "")
    else:
        venue = f.get("venue") or f.get("journal") or f.get("booktitle", "")
    venue = h(venue)

    links = []
    for label, field in (("PDF", "pdf"), ("Code", "code"),
                         ("arXiv", "arxiv"), ("Slides", "slides")):
        if f.get(field):
            links.append(f'<a href="{h(f[field])}">[{label}]</a>')
    bibtex = h_raw(clean_bibtex(e))
    links.append(
        '<details class="bibtex"><summary></summary>'
        f'<pre>{bibtex}</pre></details>'
    )

    award = f' <span class="award">({h(f["award"])})</span>' if f.get("award") else ""
    meta = f'<span class="venue">{venue}</span>' if venue else ""
    asep = "" if authors.endswith(".") else "."
    return (
        '  <li class="pub">\n'
        f'    <span class="authors">{authors}{asep}</span> '
        f'<span class="title">{title}.</span> {meta}{award}\n'
        f'    <div class="pub-links">{" ".join(links)}</div>\n'
        '  </li>'
    )


# --------------------------------------------------------------------------- #
#  Other data loaders
# --------------------------------------------------------------------------- #
def load_yaml(name):
    with open(os.path.join(DATA, name), encoding="utf-8") as f:
        return yaml.safe_load(f) or []


def sort_key_date(d):
    return str(d.get("date", "")),


# --------------------------------------------------------------------------- #
#  CV fragment generation
# --------------------------------------------------------------------------- #
def write_cv_fragments(pubs, talks, teaching, mentoring):
    os.makedirs(GEN, exist_ok=True)

    def pubs_of(t):
        items = sorted([e for e in pubs if e["pubtype"] == t],
                       key=lambda e: -e["year"])
        return "\n\n".join(cv_pub_line(e) for e in items) + "\n"

    fragments = {
        "preprints.tex": pubs_of("preprint"),
        "conference.tex": pubs_of("conference"),
        "journal.tex": pubs_of("journal"),
        "workshop.tex": pubs_of("workshop"),
    }

    # Posters (and any talks) for the CV.
    def talk_block(kind):
        items = [t for t in talks if t.get("type") == kind]
        items.sort(key=lambda t: str(t.get("date", "")), reverse=True)
        return "\n\n".join(
            f"{tex_escape(t['title'])} \\textit{{{tex_escape(t['venue'])}}}"
            for t in items
        ) + "\n"

    fragments["posters.tex"] = talk_block("poster")
    fragments["talks.tex"] = talk_block("talk")

    # "Last updated" line pinned to the bottom-center of page 1 (eso-pic).
    fragments["updated.tex"] = (
        r"\AddToShipoutPictureBG*{%" + "\n"
        r"  \AtPageLowerLeft{%" + "\n"
        r"    \put(\LenToUnit{0.5\paperwidth},\LenToUnit{0.4in}){%" + "\n"
        r"      \makebox(0,0){\footnotesize\textit{Last updated: "
        + BUILD_STAMP + r"}}}}}" + "\n"
    )

    # Teaching courses.
    tlines = []
    for c in teaching:
        s = f"{c['role']} for {c['course']} ({c['term']}), {c['institution']}"
        if c.get("enrollment"):
            s += f" (Enrollment: {c['enrollment']} students)"
        tlines.append(tex_escape(s) + r" \\")
    fragments["teaching.tex"] = "\n".join(tlines) + "\n"

    # Student advising.
    blocks = []
    for m in mentoring:
        b = [
            r"\textbf{" + tex_escape(m["name"]) + r"} \\",
            tex_escape(f"Project: {m['project']}") + r" \\",
            tex_escape(m["lab"]),
        ]
        blocks.append("\n".join(b))
    fragments["advising.tex"] = "\n\n".join(blocks) + "\n"

    for fname, content in fragments.items():
        with open(os.path.join(GEN, fname), "w", encoding="utf-8") as fp:
            fp.write(GEN_HEADER + content)


def write_cv_only_fragments(service, honors, references):
    """CV-only sections (not on the website): service, honors, references."""
    def line_list(items):
        return "\n".join(tex_escape(x) + r" \\" for x in items) + "\n"

    ref_blocks = []
    for r in references:
        head = r"\textbf{" + tex_escape(r["name"]) + "}"
        if r.get("relation"):
            head += f" ({tex_escape(r['relation'])})"
        block = [
            head + r" \\",
            r"\textbf{Appointment:} " + tex_escape(r["appointment"]) + r" \\",
            r"\textbf{Email:} " + tex_escape(r["email"]),
        ]
        ref_blocks.append("\n".join(block))

    fragments = {
        "service_department.tex": line_list(service.get("department", [])),
        "service_profession.tex": line_list(service.get("profession", [])),
        "honors.tex": line_list(honors),
        "references.tex": "\n\n".join(ref_blocks) + "\n",
    }
    for fname, content in fragments.items():
        with open(os.path.join(GEN, fname), "w", encoding="utf-8") as fp:
            fp.write(GEN_HEADER + content)


# --------------------------------------------------------------------------- #
#  HTML site generation
# --------------------------------------------------------------------------- #
NAV = [
    ("index.html", "About"),
    ("publications.html", "Publications"),
    ("talks.html", "Talks &amp; Posters"),
    ("teaching.html", "Teaching &amp; Mentoring"),
    ("cv.html", "CV"),
]


def page(active, title, body, name):
    nav = "\n".join(
        f'      <a href="{href}"{" class=\"active\"" if href == active else ""}>{label}</a>'
        for href, label in NAV
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{h(name)} — {title}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header class="site-header">
    <a class="site-name" href="index.html">{h(name)}</a>
    <nav class="site-nav">
{nav}
    </nav>
  </header>
  <main>
{body}
  </main>
  <footer class="site-footer">
    <p>Last updated {BUILD_STAMP}. &copy; {h(name)}.</p>
  </footer>
</body>
</html>
"""


def build_index(about):
    name = about.get("name", "")
    photo = about.get("photo") or ""
    photo_html = f'<img class="avatar" src="{h(photo)}" alt="{h(name)}">' if photo else ""
    bio = "\n".join(f"    <p>{h(p)}</p>" for p in about.get("bio", []))
    links = []
    for label, url in (about.get("links") or {}).items():
        if url:
            links.append(f'<a href="{h(url)}">{h(label)}</a>')
    links_html = (
        f'    <div class="links">{" · ".join(links)}</div>' if links else ""
    )
    interests = about.get("interests", "")
    interests_html = f'    <p class="interests">{h(interests)}</p>' if interests else ""
    body = f"""    <section class="hero">
      {photo_html}
      <div class="hero-text">
        <h1>{h(name)}</h1>
        <p class="tagline">{h(about.get("tagline", ""))}</p>
{interests_html}
{links_html}
      </div>
    </section>
    <section class="bio">
{bio}
    </section>"""
    return page("index.html", "About", body, name)


def build_publications(pubs, name):
    def section(label, items):
        if not items:
            return ""
        lis = "\n".join(web_pub_item(e) for e in items)
        return f'    <h2>{label}</h2>\n    <ul class="pub-list">\n{lis}\n    </ul>'

    preprints = sorted([e for e in pubs if e["pubtype"] == "preprint"],
                       key=lambda e: -e["year"])
    published = sorted([e for e in pubs if e["pubtype"] != "preprint"],
                       key=lambda e: -e["year"])
    body = "    <h1>Publications</h1>\n"
    body += section("Preprints", preprints) + "\n"
    body += section("Peer-reviewed", published)
    return page("publications.html", "Publications", body, name)


def build_talks(talks, name):
    items = sorted(talks, key=lambda t: str(t.get("date", "")), reverse=True)
    rows = []
    for t in items:
        tag = t.get("type", "talk").capitalize()
        loc = f' · {h(t["location"])}' if t.get("location") else ""
        links = []
        for label, field in (("Slides", "slides"), ("Poster", "poster"),
                             ("Video", "video")):
            url = (t.get("links") or {}).get(field)
            if url:
                links.append(f'<a href="{h(url)}">[{label}]</a>')
        links_html = f' <span class="pub-links">{" ".join(links)}</span>' if links else ""
        rows.append(
            '  <li class="talk">\n'
            f'    <span class="tag tag-{t.get("type", "talk")}">{tag}</span>\n'
            f'    <span class="title">{h(t["title"])}</span>\n'
            f'    <div class="venue">{h(t["venue"])}{loc}{links_html}</div>\n'
            '  </li>'
        )
    body = ('    <h1>Talks &amp; Posters</h1>\n'
            f'    <ul class="talk-list">\n' + "\n".join(rows) + "\n    </ul>")
    return page("talks.html", "Talks & Posters", body, name)


def build_teaching(teaching, mentoring, name):
    courses = []
    for c in teaching:
        enr = f' · Enrollment: {c["enrollment"]} students' if c.get("enrollment") else ""
        courses.append(
            '  <li class="course">\n'
            f'    <span class="title">{h(c["course"])}</span>\n'
            f'    <div class="venue">{h(c["role"])} · {h(c["institution"])} · '
            f'{h(c["term"])}{enr}</div>\n'
            '  </li>'
        )
    mentees = []
    for m in mentoring:
        mentees.append(
            '  <li class="mentee">\n'
            f'    <span class="title">{h(m["name"])}</span>'
            f' <span class="affil">{h(m["lab"])}</span>\n'
            f'    <div class="venue">{h(m["project"])}</div>\n'
            '  </li>'
        )
    body = (
        '    <h1>Teaching &amp; Mentoring</h1>\n'
        '    <h2>Courses</h2>\n'
        '    <ul class="course-list">\n' + "\n".join(courses) + "\n    </ul>\n"
        '    <h2>Student Advising</h2>\n'
        '    <ul class="mentee-list">\n' + "\n".join(mentees) + "\n    </ul>"
    )
    return page("teaching.html", "Teaching & Mentoring", body, name)


def build_cv_page(name):
    body = """    <h1>Curriculum Vitae</h1>
    <p><a class="button" href="cv.pdf" download>Download PDF</a></p>
    <object class="cv-embed" data="cv.pdf" type="application/pdf">
      <p>Your browser can't display the embedded PDF.
         <a href="cv.pdf">Download the CV here</a>.</p>
    </object>"""
    return page("cv.html", "CV", body, name)


# --------------------------------------------------------------------------- #
#  Main
# --------------------------------------------------------------------------- #
def main():
    pubs = load_publications()
    talks = load_yaml("talks.yaml")
    teaching = load_yaml("teaching.yaml")
    mentoring = load_yaml("mentoring.yaml")
    service = load_yaml("service.yaml") or {}
    honors = load_yaml("honors.yaml")
    references = load_yaml("references.yaml")
    with open(os.path.join(DATA, "about.yaml"), encoding="utf-8") as f:
        about = yaml.safe_load(f) or {}
    name = about.get("name", "")

    write_cv_fragments(pubs, talks, teaching, mentoring)
    write_cv_only_fragments(service, honors, references)

    os.makedirs(SITE, exist_ok=True)
    pages = {
        "index.html": build_index(about),
        "publications.html": build_publications(pubs, name),
        "talks.html": build_talks(talks, name),
        "teaching.html": build_teaching(teaching, mentoring, name),
        "cv.html": build_cv_page(name),
    }
    for fname, content in pages.items():
        with open(os.path.join(SITE, fname), "w", encoding="utf-8") as fp:
            fp.write(content)

    print(f"Built {len(pubs)} publications, {len(talks)} talks/posters, "
          f"{len(teaching)} courses, {len(mentoring)} mentees.")
    print(f"  -> cv/generated/*.tex")
    print(f"  -> site/*.html")


if __name__ == "__main__":
    main()
